### Listar pedidos
GET http://localhost:3002/pedidos

### Criar pedido
POST http://localhost:3002/pedidos
Content-Type: application/json

{
  "produtoId": 1,
  "quantidade": 2
}

### Buscar pedido por ID
GET http://localhost:3002/pedidos/1

### faz pedido com produto e cliente
POST http://localhost:3000/pedidos
Content-Type: application/json

{
  "produtoId": 2,
  "cliente_id": 1,
  "quantidade": 2
}