### Criar cliente
POST http://localhost:3003/clientes
Content-Type: application/json

{
  "nome": "João",
  "sobrenome": "Silva",
  "telefone": "44988887777",
  "email": "teste@email.com"
}

### listar clientes
GET http://localhost:3003/clientes

### buscar cliente por ID
GET http://localhost:3003/clientes/1
